AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Gitlotto dynamodb

Parameters:
  TheStackName:
    Type: String

Resources:

  SimpleRecords:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TableName: !Sub "${TheStackName}.simpleRecords"
      AttributeDefinitions:
        - AttributeName: partition_key
          AttributeType: S
      KeySchema:
        - AttributeName: partition_key
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  
  CompositeRecords:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TableName: !Sub "${TheStackName}.compositeRecords"
      AttributeDefinitions:
        - AttributeName: partition_key
          AttributeType: S
        - AttributeName: sort_key
          AttributeType: N
      KeySchema:
        - AttributeName: partition_key
          KeyType: HASH
        - AttributeName: sort_key
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
