AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Gitlotto storage

Parameters:
  TheStackName:
    Type: String

Resources:

  Workflows: 
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TableName: !Sub "${TheStackName}-workflows"
      AttributeDefinitions:
        - AttributeName: event_id
          AttributeType: S
        - AttributeName: target_queue_url
          AttributeType: S
        - AttributeName: start_at
          AttributeType: S
        - AttributeName: is_open
          AttributeType: S
      KeySchema:
        - AttributeName: event_id
          KeyType: HASH
        - AttributeName: target_queue_url
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: !Sub "${TheStackName}-openWorkflows"
          KeySchema:
            - AttributeName: is_open
              KeyType: HASH
            - AttributeName: start_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

Outputs:
  WorkflowsTableName:
    Description: "Workflows Table Name"
    Value: !Ref Workflows

  OpenWorkflowsIndexName:
    Description: "Open Workflows Index Name"
    # this is a shame that we have to hardcode this
    # Value: "!GetAtt Workflows.GlobalSecondaryIndexes.0.IndexName"
    Value: !Sub "${TheStackName}-openWorkflows"
