AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Gitlotto storage

Parameters:
  TheStackName:
    Type: String

Resources:

  Queue:
    Type: AWS::SQS::Queue
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties: 
      QueueName: !Sub "${TheStackName}.fifo"
      FifoQueue: true
      VisibilityTimeout: 60
      MessageRetentionPeriod: 1000000